# Generated by Django 3.1.3 on 2020-12-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_abc_to_mti_'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
